image: registry.gitlab.com/reenarobinson/swaglab-web-automation

before_script:
  #- python --version
  #- pip install -r requirements.txt
  - CHROMEDRIVER_VERSION=`google-chrome --version | grep -iEo "[0-9\.]{10,20}"`
  - wget --no-verbose -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
  - unzip /tmp/chromedriver_linux64.zip -d /opt
  - rm /tmp/chromedriver_linux64.zip
  - mv /opt/chromedriver /opt/chromedriver-$CHROMEDRIVER_VERSION
  - chmod 755 /opt/chromedriver-$CHROMEDRIVER_VERSION
  - ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION /usr/bin/chromedriver
  - export PATH=$PATH:/usr/bin/chromedriver
  - chmod 0755 /usr/bin/chromedriver
  - chmod 0755 /usr/bin/google-chrome
  - google-chrome --version
  - pip install -r requirements.txt
 
stages:
  - test
  - deploy

test:
  stage: test
  script:
    - python -m robot -v BROWSER:HeadlessChrome --variablefile Resources/configuration.yaml TESTS/PurchaseOrder.robot
  artifacts:
    when: always
    paths:
      - /builds/ReenaRobinson/swaglab-web-automation/*.html
      
pages:
  stage: deploy
  
  dependencies:
    - test

  script:
    - mkdir public
    - mv /builds/ReenaRobinson/swaglab-web-automation/*.html public
    - mv public/report.html public/index.html
  artifacts:
    when: always
    paths:
      - public