image: registry.gitlab.com/reenarobinson/swaglab-web-automation

before_script:
  - python --version
  - pip install -r requirements.txt
  - CHROMEDRIVER_VERSION=`google-chrome --version | grep -iEo "[0-9\.]{10,20}"`
  - echo $CHROMEDRIVER_VERSION
  - chmod 755 /root/.wdm/drivers/chromedriver/linux64/$CHROMEDRIVER_VERSION
  - ln -fs /root/.wdm/drivers/chromedriver/linux64/$CHROMEDRIVER_VERSION /usr/bin/chromedriver
  - export PATH=$PATH:/usr/bin/chromedriver
  - chmod 0755 /usr/bin/chromedriver
  - chmod 0755 /usr/bin/google-chrome
 
stages:
  - test
  - deploy

test:
  stage: test
  script:
    - python -m robot --variablefile Resources/configuration.yaml TESTS/PurchaseOrder.robot
  artifacts:
    when: always
    paths:
      - /builds/ReenaRobinson/swaglab-web-automation/*.html
      
pages:
  stage: deploy
  
  dependencies:
    - test

  script:
    - mkdir public
    - mv /builds/ReenaRobinson/swaglab-web-automation/*.html public
    - mv public/report.html public/index.html
  artifacts:
    when: always
    paths:
      - public